/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type AssistanceType = { 'medicalAid' : null } |
  { 'foodDistribution' : null } |
  { 'education' : null } |
  { 'generalRelief' : null } |
  { 'shelter' : null };
export type DonationStatus = { 'available' : null } |
  { 'collected' : null } |
  { 'accepted' : null };
export interface FoodDonation {
  'id' : bigint,
  'status' : DonationStatus,
  'foodItems' : string,
  'donorName' : string,
  'quantity' : bigint,
  'pickupLocation' : string,
}
export interface NGO {
  'id' : bigint,
  'status' : NGOStatus,
  'name' : string,
  'contactPerson' : string,
  'email' : string,
  'address' : string,
  'phoneNumber' : string,
  'assistanceType' : AssistanceType,
}
export type NGOStatus = { 'pending' : null } |
  { 'approved' : null } |
  { 'rejected' : null };
export interface UserProfile {
  'name' : string,
  'email' : string,
  'organization' : string,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'acceptDonation' : ActorMethod<[bigint], undefined>,
  'addFoodDonation' : ActorMethod<[string, string, bigint, string], undefined>,
  'addNGO' : ActorMethod<
    [string, string, string, string, string, AssistanceType],
    undefined
  >,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'deleteNGO' : ActorMethod<[bigint], undefined>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getDonationStatus' : ActorMethod<[bigint], [] | [DonationStatus]>,
  'getFoodDonations' : ActorMethod<[], Array<FoodDonation>>,
  'getNGOStatus' : ActorMethod<[bigint], [] | [NGOStatus]>,
  'getNGOs' : ActorMethod<[], Array<NGO>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'markDonationAsCollected' : ActorMethod<[bigint], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'updateNGO' : ActorMethod<
    [bigint, string, string, string, string, string, AssistanceType],
    undefined
  >,
  'updateNGOStatus' : ActorMethod<[bigint, NGOStatus], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];