/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const AssistanceType = IDL.Variant({
  'medicalAid' : IDL.Null,
  'foodDistribution' : IDL.Null,
  'education' : IDL.Null,
  'generalRelief' : IDL.Null,
  'shelter' : IDL.Null,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const UserProfile = IDL.Record({
  'name' : IDL.Text,
  'email' : IDL.Text,
  'organization' : IDL.Text,
});
export const DonationStatus = IDL.Variant({
  'available' : IDL.Null,
  'collected' : IDL.Null,
  'accepted' : IDL.Null,
});
export const FoodDonation = IDL.Record({
  'id' : IDL.Nat,
  'status' : DonationStatus,
  'foodItems' : IDL.Text,
  'donorName' : IDL.Text,
  'quantity' : IDL.Nat,
  'pickupLocation' : IDL.Text,
});
export const NGOStatus = IDL.Variant({
  'pending' : IDL.Null,
  'approved' : IDL.Null,
  'rejected' : IDL.Null,
});
export const NGO = IDL.Record({
  'id' : IDL.Nat,
  'status' : NGOStatus,
  'name' : IDL.Text,
  'contactPerson' : IDL.Text,
  'email' : IDL.Text,
  'address' : IDL.Text,
  'phoneNumber' : IDL.Text,
  'assistanceType' : AssistanceType,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'acceptDonation' : IDL.Func([IDL.Nat], [], []),
  'addFoodDonation' : IDL.Func([IDL.Text, IDL.Text, IDL.Nat, IDL.Text], [], []),
  'addNGO' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, AssistanceType],
      [],
      [],
    ),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'deleteNGO' : IDL.Func([IDL.Nat], [], []),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getDonationStatus' : IDL.Func(
      [IDL.Nat],
      [IDL.Opt(DonationStatus)],
      ['query'],
    ),
  'getFoodDonations' : IDL.Func([], [IDL.Vec(FoodDonation)], ['query']),
  'getNGOStatus' : IDL.Func([IDL.Nat], [IDL.Opt(NGOStatus)], ['query']),
  'getNGOs' : IDL.Func([], [IDL.Vec(NGO)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'markDonationAsCollected' : IDL.Func([IDL.Nat], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'updateNGO' : IDL.Func(
      [
        IDL.Nat,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        AssistanceType,
      ],
      [],
      [],
    ),
  'updateNGOStatus' : IDL.Func([IDL.Nat, NGOStatus], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const AssistanceType = IDL.Variant({
    'medicalAid' : IDL.Null,
    'foodDistribution' : IDL.Null,
    'education' : IDL.Null,
    'generalRelief' : IDL.Null,
    'shelter' : IDL.Null,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const UserProfile = IDL.Record({
    'name' : IDL.Text,
    'email' : IDL.Text,
    'organization' : IDL.Text,
  });
  const DonationStatus = IDL.Variant({
    'available' : IDL.Null,
    'collected' : IDL.Null,
    'accepted' : IDL.Null,
  });
  const FoodDonation = IDL.Record({
    'id' : IDL.Nat,
    'status' : DonationStatus,
    'foodItems' : IDL.Text,
    'donorName' : IDL.Text,
    'quantity' : IDL.Nat,
    'pickupLocation' : IDL.Text,
  });
  const NGOStatus = IDL.Variant({
    'pending' : IDL.Null,
    'approved' : IDL.Null,
    'rejected' : IDL.Null,
  });
  const NGO = IDL.Record({
    'id' : IDL.Nat,
    'status' : NGOStatus,
    'name' : IDL.Text,
    'contactPerson' : IDL.Text,
    'email' : IDL.Text,
    'address' : IDL.Text,
    'phoneNumber' : IDL.Text,
    'assistanceType' : AssistanceType,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'acceptDonation' : IDL.Func([IDL.Nat], [], []),
    'addFoodDonation' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Nat, IDL.Text],
        [],
        [],
      ),
    'addNGO' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, AssistanceType],
        [],
        [],
      ),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'deleteNGO' : IDL.Func([IDL.Nat], [], []),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getDonationStatus' : IDL.Func(
        [IDL.Nat],
        [IDL.Opt(DonationStatus)],
        ['query'],
      ),
    'getFoodDonations' : IDL.Func([], [IDL.Vec(FoodDonation)], ['query']),
    'getNGOStatus' : IDL.Func([IDL.Nat], [IDL.Opt(NGOStatus)], ['query']),
    'getNGOs' : IDL.Func([], [IDL.Vec(NGO)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'markDonationAsCollected' : IDL.Func([IDL.Nat], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'updateNGO' : IDL.Func(
        [
          IDL.Nat,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          AssistanceType,
        ],
        [],
        [],
      ),
    'updateNGOStatus' : IDL.Func([IDL.Nat, NGOStatus], [], []),
  });
};

export const init = ({ IDL }) => { return []; };